### ISSUE TITLE
Do not JSON decode body of  HTTP 500 errors

### ISSUE THREAD

**Issue by amorton** [datastax/astrapy#158]
Running a sample app, that is python asyc, and I got a http 500 error response from the server. Looks like astrapy tried to JSON decode a HTTP 500 response which was a HTML document:

(Note the error was caused by a development being deleted and the service returning 500) 
 
```
2024-01-08 13:02:26.465 - DEBUG   - astrapy.utils - unknown_worker - Request URL: https://3752672a-b27c-40e0-b3fd-f32888999e1d-us-west-2.apps.astra-dev.datastax.com/api/json/v1/default_keyspace/article_metadata
2024-01-08 13:02:26.465 - DEBUG   - astrapy.utils - unknown_worker - Request method: POST
2024-01-08 13:02:26.465 - DEBUG   - astrapy.utils - unknown_worker - Request headers: Headers({'host': '3752672a-b27c-40e0-b3fd-f32888999e1d-us-west-2.apps.astra-dev.datastax.com', 'accept': '*/*', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'x-cassandra-token': 'AstraCS:SGFpAPbNqqmmByWDTfQsQQYZ:9e5760f4fa32e15bd2ba4a749fbb48a96515cb36bb58ea6c2297b26591ed89a0', 'user-agent': 'astrapy/0.6.2', 'content-length': '5449', 'content-type': 'application/json'})
2024-01-08 13:02:26.465 - DEBUG   - astrapy.utils - unknown_worker - Request payload: {'findOneAndReplace': {'filter': {'_id': '1713130561'}, 'replacement': {'_id': '1713130561', 'article_metadata': {'title': 'Crime in Detroit', 'url': 'https://en.wikipedia.org/wiki/Crime_in_Detroit', 'modified_timestamp': 1703787180, 'page_id': '1713130561'}, 'chunks_metadata': {'3a3f61d5372ecaf0e2cba101246fdcf45506c98c96ae4db9': {'index': 0, 'length': 506, 'hash': '3a3f61d5372ecaf0e2cba101246fdcf45506c98c96ae4db9'}, 'adcb66e1e7aa283c2a0b936e88e24b8324579704a7a9915b': {'index': 1, 'length': 510, 'hash': 'adcb66e1e7aa283c2a0b936e88e24b8324579704a7a9915b'}, '157e0fefb9c703809ed5c89d1a42573a22fab4ef7b8ff799': {'index': 2, 'length': 510, 'hash': '157e0fefb9c703809ed5c89d1a42573a22fab4ef7b8ff799'}, 'cd93120c4150755ba48437f0efc3b9a33fa29e2506e90cba': {'index': 3, 'length': 504, 'hash': 'cd93120c4150755ba48437f0efc3b9a33fa29e2506e90cba'}, '03a0e61ae5e94e84cdcfb6e9fd01bb7bc2bf70e5d0181761': {'index': 4, 'length': 497, 'hash': '03a0e61ae5e94e84cdcfb6e9fd01bb7bc2bf70e5d0181761'}, '29a34b9801479eb84d4d2c53acd513a7f9fba3a03ab093fb': {'index': 5, 'length': 508, 'hash': '29a34b9801479eb84d4d2c53acd513a7f9fba3a03ab093fb'}, '684fd56ea8b006ba2aee15aee630161cedb3d9052b246ec1': {'index': 6, 'length': 509, 'hash': '684fd56ea8b006ba2aee15aee630161cedb3d9052b246ec1'}, 'd14cf020af39bf472c6f537afdd5dfbf96c93f90ec609bc5': {'index': 7, 'length': 511, 'hash': 'd14cf020af39bf472c6f537afdd5dfbf96c93f90ec609bc5'}, '3166f777fdabd4b6982863de59cc9336bdbaf68601ea9d3d': {'index': 8, 'length': 510, 'hash': '3166f777fdabd4b6982863de59cc9336bdbaf68601ea9d3d'}, 'f01501ce8e0cd131bd599d4b8fb57574f96eeeb6d9c66c6e': {'index': 9, 'length': 509, 'hash': 'f01501ce8e0cd131bd599d4b8fb57574f96eeeb6d9c66c6e'}, '8e60a8268adca046d1474dfe2429fbf4ec6f70d082e2dc16': {'index': 10, 'length': 508, 'hash': '8e60a8268adca046d1474dfe2429fbf4ec6f70d082e2dc16'}, '187f87d7223b7b7c878bdaa13acb5061d8b8a5cf14ba8eab': {'index': 11, 'length': 507, 'hash': '187f87d7223b7b7c878bdaa13acb5061d8b8a5cf14ba8eab'}, '9a124835435e02cd6476cd8ed74fd10b9a300368e8071f55': {'index': 12, 'length': 511, 'hash': '9a124835435e02cd6476cd8ed74fd10b9a300368e8071f55'}, 'ff45dd398b75ac3f10607caf21fdb5630db9b04652f84fc5': {'index': 13, 'length': 474, 'hash': 'ff45dd398b75ac3f10607caf21fdb5630db9b04652f84fc5'}}, 'suggested_question_chunks': [{'content': 'As of 2018, Detroit had the fourth highest murder rate among major cities in the United States after St Louis and Baltimore and the 42nd highest murder rate in the world The rate of robberies in Detroit declined by 67 between 1985 and 2014 while the rate of aggravated assaults increased As a whole, the citys crime rate has decreased considerably from its 1980s peak In 2017, there were 267 murders in Detroit down from 303 in 2016 The violent crime rate of 2,057 per 100,000 was the second highest in the', 'metadata': {'index': 0, 'length': 506, 'hash': '3a3f61d5372ecaf0e2cba101246fdcf45506c98c96ae4db9'}}, {'content': 'down from 303 in 2016 The violent crime rate of 2,057 per 100,000 was the second highest in the nation after St Louis It was roughly ten times the average rate of the suburban counties of metro Detroit which had violent crime rates below the national average of 394 per 100,000 In recent years some neighborhoods in the downtown area of Detroit have seen a significant decline in crime, while the crime rate remains very high in most of the city and has a significant impact on daily life History In June 1971,', 'metadata': {'index': 1, 'length': 510, 'hash': 'adcb66e1e7aa283c2a0b936e88e24b8324579704a7a9915b'}}, {'content': 'very high in most of the city and has a significant impact on daily life History In June 1971, the largest mass murder in Detroits history occurred, known as the Hazelwood massacre Eight AfricanAmericans were shot and killed in a house in the Virginia Park Historic District The number of Detroit homicides peaked in 1974 at 714 and again in 1991 with 615 At the end of 2010, the homicide count fell to 308 for the year with an estimated population of just over 700,000, the lowest count and rate since 1967 In', 'metadata': {'index': 2, 'length': 510, 'hash': '157e0fefb9c703809ed5c89d1a42573a22fab4ef7b8ff799'}}, {'content': 'the year with an estimated population of just over 700,000, the lowest count and rate since 1967 In 2006, the Detroit Police Departments Crime Analysis Unit reported that crimes dropped by 24 percent since the introduction of casino gaming to Detroit, Michigan In a 2007 analysis, Detroit officials noted that about 65 to 70 percent of homicides in the city were confined to a narcotics catalyst In 2013, Detroits number of criminal homicides was 333, a reduction of 14 compared to 2012 However, taken in', 'metadata': {'index': 3, 'length': 504, 'hash': 'cd93120c4150755ba48437f0efc3b9a33fa29e2506e90cba'}}, {'content': 'Detroits number of criminal homicides was 333, a reduction of 14 compared to 2012 However, taken in context by population, Detroit remains a city with one of the highest homicide rates per capita in the United States In April 2008, Detroit unveiled a 300million stimulus plan to create jobs and revitalize neighborhoods, financed by city bonds and paid for by earmarking about 15 of the wagering tax Detroits plans for revitalization include 7MileLivernois, Brightmoor, East English Village, Grand', 'metadata': {'index': 4, 'length': 497, 'hash': '03a0e61ae5e94e84cdcfb6e9fd01bb7bc2bf70e5d0181761'}}]}, 'options': {'upsert': True}, 'sort': {}}}
2024-01-08 13:02:26.465 - DEBUG   - astrapy.utils - unknown_worker - Response status code: 500
2024-01-08 13:02:26.465 - DEBUG   - astrapy.utils - unknown_worker - Response headers: Headers({'server': 'nginx/1.21.4', 'date': 'Mon, 08 Jan 2024 00:02:26 GMT', 'content-type': 'text/html', 'content-length': '170', 'connection': 'keep-alive'})
2024-01-08 13:02:26.465 - DEBUG   - astrapy.utils - unknown_worker - Response content: <html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx</center>
</body>
</html>

2024-01-08 13:02:26.467 - DEBUG   - httpcore.http11 - unknown_worker - receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Server', b'nginx/1.21.4'), (b'Date', b'Mon, 08 Jan 2024 00:02:26 GMT'), (b'Content-Type', b'application/json;charset=UTF-8'), (b'Content-Length', b'26'), (b'Connection', b'keep-alive')])
2024-01-08 13:02:26.468 - INFO    - httpx - unknown_worker - HTTP Request: POST https://3752672a-b27c-40e0-b3fd-f32888999e1d-us-west-2.apps.astra-dev.datastax.com/api/json/v1/default_keyspace/article_metadata "HTTP/1.1 200 OK"
2024-01-08 13:02:26.468 - DEBUG   - httpcore.http11 - unknown_worker - receive_response_body.started request=<Request [b'POST']>
2024-01-08 13:02:26.468 - DEBUG   - httpcore.http11 - unknown_worker - receive_response_body.complete
2024-01-08 13:02:26.468 - DEBUG   - httpcore.http11 - unknown_worker - response_closed.started
2024-01-08 13:02:26.468 - DEBUG   - httpcore.http11 - unknown_worker - response_closed.complete
2024-01-08 13:02:26.468 - DEBUG   - astrapy.utils - unknown_worker - Request URL: https://3752672a-b27c-40e0-b3fd-f32888999e1d-us-west-2.apps.astra-dev.datastax.com/api/json/v1/default_keyspace/article_metadata
2024-01-08 13:02:26.468 - DEBUG   - astrapy.utils - unknown_worker - Request method: POST
2024-01-08 13:02:26.468 - DEBUG   - astrapy.utils - unknown_worker - Request headers: Headers({'host': '3752672a-b27c-40e0-b3fd-f32888999e1d-us-west-2.apps.astra-dev.datastax.com', 'accept': '*/*', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'x-cassandra-token': 'AstraCS:SGFpAPbNqqmmByWDTfQsQQYZ:9e5760f4fa32e15bd2ba4a749fbb48a96515cb36bb58ea6c2297b26591ed89a0', 'user-agent': 'astrapy/0.6.2', 'content-length': '91', 'content-type': 'application/json'})
2024-01-08 13:02:26.468 - DEBUG   - astrapy.utils - unknown_worker - Request payload: {'findOne': {'filter': {'_id': '1713130559'}, 'projection': {}, 'options': {}, 'sort': {}}}
2024-01-08 13:02:26.468 - DEBUG   - astrapy.utils - unknown_worker - Response status code: 200
2024-01-08 13:02:26.468 - DEBUG   - astrapy.utils - unknown_worker - Response headers: Headers({'server': 'nginx/1.21.4', 'date': 'Mon, 08 Jan 2024 00:02:26 GMT', 'content-type': 'application/json;charset=UTF-8', 'content-length': '26', 'connection': 'keep-alive'})
2024-01-08 13:02:26.469 - DEBUG   - astrapy.utils - unknown_worker - Response content: {"data":{"document":null}}
2024-01-08 13:02:26.465 - ERROR   - root - store_article_diff-0 - Error in worker store_article_diff-0
Traceback (most recent call last):
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/v2/utils.py", line 52, in _worker
    result = await self.func(item)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/v2/process.py", line 256, in store_article_diff
    await update_article_metadata(article_diff)
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/v2/process.py", line 345, in update_article_metadata
    resp = await utils.wrap_blocking_io(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/v2/utils.py", line 19, in wrap_blocking_io
    return await loop.run_in_executor(None, func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/.pyenv/versions/3.12.1/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/v2/process.py", line 346, in <lambda>
    lambda x: METADATA_COLLECTION.find_one_and_replace(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/.venv/lib/python3.12/site-packages/astrapy/db.py", line 369, in find_one_and_replace
    response = self._request(
               ^^^^^^^^^^^^^^
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/.venv/lib/python3.12/site-packages/astrapy/db.py", line 92, in _request
    responsebody = cast(API_RESPONSE, response.json())
                                      ^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/.venv/lib/python3.12/site-packages/httpx/_models.py", line 761, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/.pyenv/versions/3.12.1/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/.pyenv/versions/3.12.1/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/.pyenv/versions/3.12.1/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-01-08 13:02:26.473 - DEBUG   - aiohttp_sse_client2.client - unknown_worker - close
2024-01-08 13:02:26.498 - ERROR   - asyncio - unknown_worker - Task exception was never retrieved
future: <Task finished name='store_article_diff-0' coro=<AsyncStep._worker() done, defined at /Users/aaron.morton/code/riptano/wikipedia-scripts/v2/utils.py:47> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/v2/utils.py", line 52, in _worker
    result = await self.func(item)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/v2/process.py", line 256, in store_article_diff
    await update_article_metadata(article_diff)
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/v2/process.py", line 345, in update_article_metadata
    resp = await utils.wrap_blocking_io(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/v2/utils.py", line 19, in wrap_blocking_io
    return await loop.run_in_executor(None, func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/.pyenv/versions/3.12.1/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/v2/process.py", line 346, in <lambda>
    lambda x: METADATA_COLLECTION.find_one_and_replace(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/.venv/lib/python3.12/site-packages/astrapy/db.py", line 369, in find_one_and_replace
    response = self._request(
               ^^^^^^^^^^^^^^
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/.venv/lib/python3.12/site-packages/astrapy/db.py", line 92, in _request
    responsebody = cast(API_RESPONSE, response.json())
                                      ^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/.venv/lib/python3.12/site-packages/httpx/_models.py", line 761, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/.pyenv/versions/3.12.1/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/.pyenv/versions/3.12.1/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/.pyenv/versions/3.12.1/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/wiki_articles.py", line 196, in <module>
    asyncio.run(listen_for_changes())
  File "/Users/aaron.morton/.pyenv/versions/3.12.1/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/.pyenv/versions/3.12.1/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/.pyenv/versions/3.12.1/lib/python3.12/asyncio/base_events.py", line 671, in run_until_complete
    self.run_forever()
  File "/Users/aaron.morton/.pyenv/versions/3.12.1/lib/python3.12/asyncio/base_events.py", line 638, in run_forever
    self._run_once()
  File "/Users/aaron.morton/.pyenv/versions/3.12.1/lib/python3.12/asyncio/base_events.py", line 1971, in _run_once
    handle._run()
  File "/Users/aaron.morton/.pyenv/versions/3.12.1/lib/python3.12/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/v2/utils.py", line 59, in _worker
    sys.exit(1)
SystemExit: 1
```

**Comment by erichare** [comment]
Fixed in #128 please confirm when you can!
