### ISSUE TITLE
upsert() function does not correctly handle errors

### ISSUE THREAD

**Issue by amorton** [datastax/astrapy#159]
using the upsert() function I got this error.

The code in the client checks if there was an existing document error, but does not check if any other error occured. 

See https://github.com/datastax/astrapy/blob/master/astrapy/db.py#L812

```
2024-01-09 07:47:04.364 - DEBUG   - astrapy.utils - unknown_worker - Response content: {"status":{"insertedIds":[]},"errors":[{"message":"Failed to insert document with _id 'recent_articles': Cassandra timeout during CAS write query at consistency LOCA
L_SERIAL (2 replica were required but only 1 acknowledged the write)"}]}
2024-01-09 07:47:04.364 - ERROR   - root - store_article_diff-1 - Error in worker store_article_diff-1
Traceback (most recent call last):
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/v2/utils.py", line 52, in _worker
    result = await self.func(item)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/v2/process.py", line 266, in store_article_diff
    await update_article_metadata(article_diff)
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/v2/process.py", line 373, in update_article_metadata
    resp = await utils.wrap_blocking_io(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/v2/utils.py", line 19, in wrap_blocking_io
    return await loop.run_in_executor(None, func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/.pyenv/versions/3.12.1/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/v2/process.py", line 374, in <lambda>
    lambda x: SUGGESTIONS_COLLECTION.upsert(x),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.morton/code/riptano/wikipedia-scripts/.venv/lib/python3.12/site-packages/astrapy/db.py", line 720, in upsert
    upserted_id = cast(str, result["status"]["insertedIds"][0])
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

```

**Comment by cbornet** [comment]
Can you test with astrapy 0.7 ? Error management has been reviewed.
Also, since you're using asyncio you may be able to use the new `AsyncDB` interface.

**Comment by hemidactylus** [comment]
I just investigated a bit on the error and, well, 0.7 would not fix it yet.
The reason is, upsert conflates into a whole check _if there's error and the error is doc-already-exists_. Else, it does the update-existing-doc.
So if the error is something other than "doc already exists" we get the error.

I have a fix coming, it's ready (reworked the flow around failures during upsert method).

Two observations:

- I don't like having to raise a `ValueError` but short of a bigger refactoring of the request handling this is what we can do (the reason is the APIException needs an httpx request in the constructor, and the upsert has no access on that one. Another option would be to provide an explicit list of error codes to skip to the request method. This would be better and keep layers separate better. But see next point)
- There is now a better way to do upserts (see #168) so, until that one is implemented in astrapy, the fix I'm about to submit is good enough (as long as one temporarily catches for ValueErrors and not for APIRequestErrors in their upsert-calling code).
-
