### ISSUE TITLE
create_collection, *and everything on it*, should support nonvector collections

### ISSUE THREAD

**Issue by hemidactylus** [datastax/astrapy#98]
As of 0.6.0,

```
astra_db.create_collection("novectors")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stefano/personal/WORK_Datastax/Code/other_github/astrapy/astrapy/db.py", line 798, in create_collection
    self._request(
  File "/home/stefano/personal/WORK_Datastax/Code/other_github/astrapy/astrapy/db.py", line 725, in _request
    raise ValueError(json.dumps(responsebody["errors"]))
ValueError: [{"message": "Cannot invoke \"java.lang.Integer.intValue()\" because the return value of \"io.stargate.sgv2.jsonapi.api.model.command.impl.CreateCollectionCommand$Options$VectorSearchConfig.dimension()\" is null"}]
```

the reason is that the method creates an incomplete `options = {"vector": {}}`, which makes the API angry.

1. Support for nonvectors in create_collection
2. go through all methods on collection and make sure they are ok with there _not_ being a vector
3. specific tests

**Comment by hemidactylus** [comment]
Working on it on branch `feature/#98-nonvector-collections`, so far only a draft for point 1
